###* Test
GET http://localhost:4321/api/test

###* Sign up
POST http://localhost:4321/api/rpc/auth/sign-up/email
Content-Type: application/json
Origin: http://localhost:4321

{
    "email": "igor@gmail.com",
    "password": "11",
    "name": "Igor"
}

###* Sign In
POST http://localhost:4321/api/rpc/auth/sign-in/email
Content-Type: application/json
Origin: http://localhost:4321

{
    "email": "igor7786@gmail.com",
    "password": "1234"
}
###* Sign out
POST  http://localhost:4321/api/rpc/auth/sign-out
Content-Type: application/json
Origin: http://localhost:4321

{
    "password": "11"
}
###* Delete User
POST http://localhost:4321/api/auth/delete-user
Content-Type: application/json
Origin: http://localhost:4321

{
    "password": "11"
}

###* Create Todo
POST http://localhost:4321/api/todos
Content-Type: application/json
Origin: http://localhost:4321

{
    "title": "Todo ",
    "description": "Description 1",
    "completed": false
}

###* Get Todos
GET http://localhost:4321/api/rpc/get-todos
Content-Type: application/json
Origin: http://localhost:4321
