version: "3.9"

services:
  # FastAPI application 1
  app1:
    build:
      context: .
      dockerfile: backend/fastapi-app.dockerfile
    image: my-python-app1
    container_name: my-python-app1-container
    env_file:
      - ./backend/.env
    command: ["/backend/boot/run-fastapi.sh"]
    volumes:
      - ./backend/app_db:/backend/app_db  # Shared database
      - ./backend/app_main:/backend/app_main:ro  # Read-only codebase
    networks:
      - my_network  # Use the custom network
    dns:
      - 8.8.8.8  # Use Google Public DNS
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./backend/app_main
          target: /backend/app_main
          ignore:
            - __pycache__/
        - action: rebuild
          path: ./backend/requirements.txt

  #FastAPI application 2
  app2:
    build:
      context: .
      dockerfile: backend/fastapi-app.dockerfile
    image: my-python-app2
    container_name: my-python-app2-container
    env_file:
      - ./backend/.env
    command: ["/backend/boot/run-fastapi.sh"]
    volumes:
      - ./backend/app_db:/backend/app_db
      - ./backend/app_main:/backend/app_main:ro
    networks:
      - my_network  # Use the custom network
    dns:
      - 8.8.8.8  # Use Google Public DNS
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./backend/app_main
          target: /backend/app_main
          ignore:
            - __pycache__/
        - action: rebuild
          path: ./backend/requirements.txt

  #FastAPI application 3
  app3:
    build:
      context: .
      dockerfile: backend/fastapi-app.dockerfile
    image: my-python-app3
    container_name: my-python-app3-container
    env_file:
      - ./backend/.env
    command: ["/backend/boot/run-fastapi.sh"]
    volumes:
      - ./backend/app_db:/backend/app_db
      - ./backend/app_main:/backend/app_main:ro
    networks:
      - my_network  # Use the custom network
    dns:
      - 8.8.8.8  # Use Google Public DNS
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./backend/app_main
          target: /backend/app_main
          ignore:
            - __pycache__/
        - action: rebuild
          path: ./backend/requirements.txt

  #My Astro app (Node.js app)
  astro-app:
    build:
      context: .
      dockerfile: ./frontend/astro-app.dockerfile  # Ensure this is the correct path to your Dockerfile
    container_name: my-astro-app-container
    command: ["npm", "run", "dev"]
    # for production
#    command: ["node", "./dist/server/entry.mjs"]
    volumes:
      - ./frontend:/frontend  # Mount the local frontend directory to the container for live updates
    depends_on:
      - app1
      - app2
      - app3
    networks:
#      - my_network
      my_network:
        ipv4_address: 192.168.1.7
    dns:
      - 8.8.8.8  # Use Google Public DNS
    restart: unless-stopped

  # N8n application
  n8n:
    build:
      context: .
      dockerfile: n8n/n8n-app.dockerfile
    image: my-n8n
    container_name: my-n8n-container
    env_file:
      - ./n8n/.env
    command: ["start"]
    volumes:
      - ./n8n/n8n_data:/home/node/.n8n
#      - n8n_data:/home/node/.n8n
#      - ./local-files:/files
    restart: unless-stopped
    networks:
      - my_network

  # Portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
#      - portainer_data:/data
    networks:
      - my_network  # Use the custom network
  # Nginx web server (acting as a reverse proxy)
  nginx:
    build:
      context: .
      dockerfile: nginx/nginx-app.dockerfile
    image: my-nginx
    container_name: my-nginx-container
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
#    command: ["nginx", "-g", "daemon off;"]
    command: ["/etc/nginx/run-nginx.sh"]
    env_file:
      - ./backend/.env
      - ./frontend/.env
      - ./n8n/.env
      - ./.env
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
#      - "9000:9000"  # Portainer
#      - "5678:5678"  # N8n
#      - "4321:4321"  # Astro
      #- "5173:5173"  # Vite
    depends_on:
      - astro-app  # Uncommented to ensure Nginx can proxy requests to the Astro app
      - n8n  # Uncommented to ensure Nginx can proxy requests to the N8n app
      - portainer # Uncommented to ensure Nginx can proxy requests to the Portainer app
    networks:
      - my_network  # Use the custom network
    dns:
      - 8.8.8.8  # Use Google Public DNS
    restart: unless-stopped


# Define the shared network between all containers
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

# Define the volume shared for database persistence
volumes:
  app_db:
    driver: local
  n8n_data:
    driver: local
  portainer_data:
    driver: local