version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: fastApi.dockerfile
    image: my-python-app
    container_name: my-python-app-container
    ports:
      - "8080:8080"
    volumes:
      - ./app_db:/backend/app_db  # Bidirectional sync for the database
      - ./app_main:/backend/app_main:ro  # Read-only mount for app_main
    restart: unless-stopped