version: "3.9"
services:
  app1:
    build:
      context: .
      dockerfile: fastapi-app.dockerfile
    image: my-python-app
    container_name: my-python-app1-container
    volumes:
      - ./app_db:/backend/app_db  # Shared database
      - ./app_main:/backend/app_main:ro  # Read-only codebase
    networks:
      - my_network
    restart: always  # Ensure container auto-restarts on failure or reboot

  app2:
    build:
      context: .
      dockerfile: fastapi-app.dockerfile
    image: my-python-app
    container_name: my-python-app2-container
    volumes:
      - ./app_db:/backend/app_db
      - ./app_main:/backend/app_main:ro
    networks:
      - my_network
    restart: always

  app3:
    build:
      context: .
      dockerfile: fastapi-app.dockerfile
    image: my-python-app
    container_name: my-python-app3-container
    volumes:
      - ./app_db:/backend/app_db
      - ./app_main:/backend/app_main:ro
    networks:
      - my_network
    restart: always

  web:
    build:
      context: .
      dockerfile: nginx-app.dockerfile
    image: my-nginx
    container_name: my-nginx-container
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
volumes:
  app_db:
    driver: local